// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjj5hT9TzWgWRN5RuQk-C6vJxuPm8kmGc',
    appId: '1:454072033057:web:87e4fafe61067288b6e860',
    messagingSenderId: '454072033057',
    projectId: 'kasir-cafe-2e45b',
    authDomain: 'kasir-cafe-2e45b.firebaseapp.com',
    storageBucket: 'kasir-cafe-2e45b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjYxU9BRS1KzgycMCQVv8S12sb97w1tFk',
    appId: '1:454072033057:android:dc437c0aec6d5b85b6e860',
    messagingSenderId: '454072033057',
    projectId: 'kasir-cafe-2e45b',
    storageBucket: 'kasir-cafe-2e45b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnb0lZQLdebq1gsWRsQ-SHDhAqRYm-eJw',
    appId: '1:454072033057:ios:4a50b69e5d2704beb6e860',
    messagingSenderId: '454072033057',
    projectId: 'kasir-cafe-2e45b',
    storageBucket: 'kasir-cafe-2e45b.firebasestorage.app',
    iosBundleId: 'com.example.kasirCafe',
  );
}
